---
environments:
  example:
    environment_variables:
      EXAMPLE_DEPLOYMENT: testing
pipelines:
  MavenBuild:
    group: RestServiceDeliveryPipeline
    materials:
      myPluggableGit:
        destination: restservice
        scm: restservice-scm-id
    # stages:
    #   - build: # build the app
    #       jobs:
    #         build: # name of the job
    #           tasks:
    #            - exec: # Give the app a few seconds to finish initialisig
    #                command: pwd

    stages:
      - build:
          jobs:
            build:
              tasks:
                - exec:
                    arguments:
                      - clean
                      - test
                    command: mvn
      # -
      #   Compile:
      #     jobs:
      #       compile:
      #         tasks:
      #           -
      #             arguments:
      #               - clean
      #               - package
      #             command: mvn
      #             exec: ~
      # -
      #   Deploy:
      #     jobs:
      #       deploy:
      #         tasks:
      #           -
      #             arguments:
      #               - "-c"
      #               - "cp packer/restservicejavamaven.json target/restservicejavamaven-0.0.1-SNAPSHOT.deb /Users/uritzry/GoCDPOC"
      #             command: /bin/sh
      #             exec: ~
