---
environments:
  example:
    environment_variables:
      EXAMPLE_DEPLOYMENT: testing
pipelines:
  MavenBuild:
    group: RestServiceDeliveryPipeline
    materials:
      myPluggableGit:
        destination: restservicejavamaven
        scm: restservicejavamaven-scm-id
    stages:
      -
        Verify:
          jobs:
            CodeCoverage:
              tasks:
                -
                  exec:
                    arguments:
                      - clean
                      - test
                    command: mvn
      -
        Compile:
          jobs:
            compile:
              tasks:
                -
                  arguments:
                    - clean
                    - package
                  command: mvn
                  exec: ~
      -
        Deploy:
          jobs:
            deploy:
              tasks:
                -
                  arguments:
                    - "-c"
                    - "cp packer/restservicejavamaven.json target/restservicejavamaven-0.0.1-SNAPSHOT.deb /Users/uritzry/GoCDPOC"
                  command: /bin/sh
                  exec: ~
